name: "Runtime Upgrade Action"
description: "Perform a runtime upgrade on a Substrate-based chain using Polkadot JS API"
inputs:
  targetChainUrl:
    description: 'Target chain WSS URL'
    required: true
  wasmPath:
    description: 'WASM file link or path'
    required: true
  account:
    description: 'Account secret/mnemonic to sign the upgrade'
    required: false
  relaychainUrl:
    description: 'Relaychain WSS URL (if account is relaychain sudo)'
    required: false
  dryRun:
    description: 'Validate inputs but do not submit any transactions'
    default: 'false'
    required: false
runs:
  using: "node20"
  main: "dist/index.js"